services:
  app:
    build:
      target: development
    volumes:
      - ./src:/app/src:cached
      - ./tests:/app/tests:cached
      - ./alembic:/app/alembic:cached
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DB_ECHO=true
    command: ["uvicorn", "src.app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
